name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter doctor
      - name: Test
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter test
  build_android_apk:
    name: Build android apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter doctor
      - name: Decrypt archive
        env:
          ARCHIVE_PASSPHRASE: ${{ secrets.ARCHIVE_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase "$ARCHIVE_PASSPHRASE" --output "archive.tar" archive.tar.gpg
          tar -xf archive.tar
          rm archive.tar
      - name: Build apk
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build_android_appbundle:
    name: Build android appbundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter doctor
      - name: Decrypt archive
        env:
          ARCHIVE_PASSPHRASE: ${{ secrets.ARCHIVE_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase "$ARCHIVE_PASSPHRASE" --output "archive.tar" archive.tar.gpg
          tar -xf archive.tar
          rm archive.tar
      - name: Build appbundle
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter build appbundle
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  build_web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter config --enable-web
          ~/Tools/flutter/bin/flutter doctor
      - name: Build web
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter build web
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter config --enable-windows-desktop
          ~/Tools/flutter/bin/flutter doctor
        shell: bash
      - name: Build windows
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter build windows
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build\windows\runner\Release
